// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
)

func (s *ResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/FormData
type FormData struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Subject         string `json:"subject"`
	Message         string `json:"message"`
	CaptchaSolution string `json:"captchaSolution"`
}

// GetName returns the value of Name.
func (s *FormData) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *FormData) GetEmail() string {
	return s.Email
}

// GetSubject returns the value of Subject.
func (s *FormData) GetSubject() string {
	return s.Subject
}

// GetMessage returns the value of Message.
func (s *FormData) GetMessage() string {
	return s.Message
}

// GetCaptchaSolution returns the value of CaptchaSolution.
func (s *FormData) GetCaptchaSolution() string {
	return s.CaptchaSolution
}

// SetName sets the value of Name.
func (s *FormData) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *FormData) SetEmail(val string) {
	s.Email = val
}

// SetSubject sets the value of Subject.
func (s *FormData) SetSubject(val string) {
	s.Subject = val
}

// SetMessage sets the value of Message.
func (s *FormData) SetMessage(val string) {
	s.Message = val
}

// SetCaptchaSolution sets the value of CaptchaSolution.
func (s *FormData) SetCaptchaSolution(val string) {
	s.CaptchaSolution = val
}

type FormPostBadRequest Response

func (*FormPostBadRequest) formPostRes() {}

// FormPostInternalServerError is response for FormPost operation.
type FormPostInternalServerError struct{}

func (*FormPostInternalServerError) formPostRes() {}

type FormPostOK Response

func (*FormPostOK) formPostRes() {}

type FormPostUnprocessableEntity Response

func (*FormPostUnprocessableEntity) formPostRes() {}

// Ref: #/components/schemas/Response
type Response struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Response) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Response) SetMessage(val string) {
	s.Message = val
}

// ResponseStatusCode wraps Response with StatusCode.
type ResponseStatusCode struct {
	StatusCode int
	Response   Response
}

// GetStatusCode returns the value of StatusCode.
func (s *ResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ResponseStatusCode) GetResponse() Response {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ResponseStatusCode) SetResponse(val Response) {
	s.Response = val
}
