// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func encodeFormPostRequest(
	req *FormData,
	r *http.Request,
) error {
	const contentType = "application/x-www-form-urlencoded"
	request := req

	q := uri.NewFormEncoder(map[string]string{})
	{
		// Encode "name" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(request.Name))
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "email" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "email",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(request.Email))
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "subject" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "subject",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(request.Subject))
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "message" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "message",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(request.Message))
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "frc-captcha-solution" form field.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "frc-captcha-solution",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}
		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(request.FrcMinusCaptchaMinusSolution))
		}); err != nil {
			return errors.Wrap(err, "encode query")
		}
	}
	encoded := q.Values().Encode()
	ht.SetBody(r, strings.NewReader(encoded), contentType)
	return nil
}
