// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// FormPost implements POST /form operation.
//
// Validates form and sends SMTP mail on success.
//
// POST /form
func (UnimplementedHandler) FormPost(ctx context.Context, req *FormData) (r FormPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ResponseStatusCode) {
	r = new(ResponseStatusCode)
	return r
}
